src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/blueprint.json, src/main/resources/templates/credentials_azure.json, src/main/resources/templates/credentials_ec2.json, src/main/resources/templates/credentials_gcc.json, src/main/resources/templates/stack.json, src/main/resources/templates/template_azure.json, src/main/resources/templates/template_ec2.json, src/main/resources/templates/template_gcc.json, src/main/resources/templates/template_spot_ec2.json
depends on https://github.com/sequenceiq/cloudbreak/pull/412
=> CLOUD-387 added publicInAccount params to JSONs

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/blueprint.json, src/main/resources/templates/credentials_azure.json, src/main/resources/templates/credentials_ec2.json, src/main/resources/templates/credentials_gcc.json, src/main/resources/templates/stack.json, src/main/resources/templates/template_azure.json, src/main/resources/templates/template_ec2.json, src/main/resources/templates/template_gcc.json, src/main/resources/templates/template_spot_ec2.json
Heterogen cluster changes was merged into cloudbreak so I updated the rest client with the API changes.
Pls @keyki or @martonsereg review this pr.
After the merge I will send the pr for the Cloudbreak-shell.
=> Heterogen cluster

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stackimage.json
=> CLOUD-338 added image to stack post

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json
=> CLOUD-422 added failure handling support

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-484 get resources by name (in account)

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
@doktoric 
stack is not here, because stack will be deleted by id (retrieve it by name, then obtain its id )
=> CLOUD-484 add delete resources by name methods

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json
=> CLOUD-470 added stack parameters

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/cluster.json, src/main/resources/templates/stack_nodecount_put.json
Needed if sequenceiq/cloudbreak#490 is merged
=> API changes related to host group domain

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/template_ec2.json, src/main/resources/templates/template_spot_ec2.json
=> CLOUD-433 encrypted volume possibility added

build.gradle, src/main/groovy/com/sequenceiq/cloudbreak/main/CloudbreakClientMain.groovy, src/main/java/com/sequenceiq/cloudbreak/main/CloudbreakClientMain.java, src/main/java/com/sequenceiq/cloudbreak/main/VersionedApplication.java
=> CLOUD-515 added version check possibility

src/main/java/com/sequenceiq/cloudbreak/main/CloudbreakClientMain.java, src/main/java/com/sequenceiq/cloudbreak/main/VersionedApplication.java
=> CLOUD-515 version class changes

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-545 added gateway support

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/credentials_openstack.json, src/main/resources/templates/template_openstack.json
=> CLOUD-559 implemented openstack

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/cluster_status_put.json, src/main/resources/templates/stack_status_put.json, src/main/resources/templates/template_gcc.json
=> CLOUD-614: stack, cluster start/stop, CLOUD-616: GCP Template creation extend with volumetype param, CLOUD-617: Detailed stack status retrieval

src/main/resources/templates/template_gcc.json
=> CLOUD-616: volumeType fix

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/networks_aws.json, src/main/resources/templates/networks_azure.json, src/main/resources/templates/networks_gcp.json, src/main/resources/templates/networks_openstack.json, src/main/resources/templates/stack.json, src/main/resources/templates/template_openstack.json
@akanto or @doktoric 
Please take a look!
This pull depends on https://github.com/sequenceiq/cloudbreak/pull/623
=> CLOUD-676 add network endpoints

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json, src/main/resources/templates/stackimage.json
=> CLOUD-785 specify disk per storage in case of Azure

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-836 add support for dedicated instances on AWS

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json
=> Security resource

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-885 added get stack certificate method

build.gradle
@keyki plz review and delete branch
=> CLOUD-41495 - Upgrade groovy to 2.4.4

build.gradle, src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/cluster.json
=> CLOUD-41495 Enable security at postCluster()

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-41495 Fix kerberos related default values

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/cluster.json
=> CLOUD-41495 Fix cluster.json

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/credentials_azure_rm.json
=> CLOUD-42308 added azure rm support

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/cluster.json
=> CLOUD-44310 added filesystem to cluster post

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json, src/main/resources/templates/stackimage.json
=> CLOUD-44526 Introduce cloud platform variant in cloudbreak api

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-45515: new func: post security group

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-45515: no null check is needed

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
@mhmxs or @doktoric pls review
=> CLOUD-45515: missing Exception from postSecurityGroup()

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-45515: return id instead of  HttpResponse

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/stack.json, src/main/resources/templates/stackimage.json
=> CLOUD-45130 added av zone

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-47610 create security group

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> CLOUD-46697 Refactor platform parameters

src/main/resources/templates/template_azure.json, src/main/resources/templates/template_ec2.json, src/main/resources/templates/template_gcp.json, src/main/resources/templates/template_openstack.json, src/main/resources/templates/template_spot_ec2.json
@akanto there is no branch for 1.1 release
=> CLOUD-48916 generic platform entities

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy
=> update azure template type to AZURE_RM

src/main/groovy/com/sequenceiq/cloudbreak/client/CloudbreakClient.groovy, src/main/resources/templates/credentials_azure.json
=> CLOUD-46109 Full removal of old azure implementation
